before_script:
    - sudo apt-get install apache2
    - composer self-update
    - composer install
language: php
branches:
  only:
  - master
php:
    - 7.1
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
